[package]
name = "aws-cloudwatchlogs-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.56.1"
aws-sdk-cloudwatchlogs = "0.34.0"
tokio = { version = "1", features = ["full"] }